# Geographic Hotspot Identification for Migration

## Description
This project will explore how visualization and spatial analytics can reveal geographic “hotspots” of migration risk using open data. The core idea is to combine multiple socioeconomic and environmental indicators — such as poverty, unemployment, education levels, remittances, and climate risk — into a composite migration-risk score for each region. The focous will be Latin America and the Caribbean.

In [1]:
# imports
import altair as alt
alt.data_transformers.disable_max_rows()
import polars as pl
from pathlib import Path
from vega_datasets import data
import geopandas as gpd
import os, sys
sys.path.insert(0, os.path.abspath(".."))

In [2]:
migrants_stock = pl.read_csv(Path("../Data/migrants_stock_undesa.csv"))
migrants_stock

shape: (56_060, 16)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ 2010        ┆ 2015        ┆ 2020        ┆ 2024       │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ str         ┆ str         ┆ str         ┆ str        │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 1     ┆ World       ┆ null     ┆ null ┆ … ┆ 113 256 786 ┆ 130 187 624 ┆ 143 223 497 ┆ 158 009    │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 795        │
│ 2     ┆ World       ┆ null     ┆ null ┆ … ┆ 9 739 644   ┆ 12 066 851  ┆ 14 375 255  ┆ 16 046 945 │
│ 3     ┆ World       ┆ null     ┆ null ┆ … ┆ 14 628 780  ┆ 18 783 440  ┆ 21 212 741  ┆ 22 913 639 │
│ 4     ┆ World       ┆ null     ┆ null ┆ … ┆ 23 546 473  ┆ 28 740 559  ┆ 30 263 324  ┆ 33 260 124 │
│ 5     ┆ World       ┆ null     ┆ null ┆ … ┆ 13 840 573  ┆ 15 768 936  ┆ 17 926 170  ┆ 19 677 034 │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 28026 ┆ Wallis and  ┆ 44       ┆ B R  ┆ … ┆ 545         ┆ 513         ┆ 512         ┆ 510        │
│       ┆ Futuna      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands*    ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 28027 ┆ Wallis and  ┆ 44       ┆ B R  ┆ … ┆ 68          ┆ 34          ┆ 28          ┆ 28         │
│       ┆ Futuna      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands*    ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 28028 ┆ Wallis and  ┆ 44       ┆ B R  ┆ … ┆ 9           ┆ 7           ┆ 5           ┆ 5          │
│       ┆ Futuna      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands*    ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 28029 ┆ Wallis and  ┆ 44       ┆ B R  ┆ … ┆ 9           ┆ 7           ┆ 5           ┆ 5          │
│       ┆ Futuna      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands*    ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 28030 ┆ Wallis and  ┆ 44       ┆ B R  ┆ … ┆ 12          ┆ 15          ┆ 13          ┆ 13         │
│       ┆ Futuna      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands*    ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [3]:
country_codes = pl.read_csv(Path("../Data/country_codes.csv"),ignore_errors=True)
country_codes

shape: (249, 12)
┌────────────┬─────────┬─────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ name       ┆ alpha-2 ┆ alpha-3 ┆ country-co ┆ … ┆ intermedia ┆ region-co ┆ sub-regio ┆ intermedi │
│ ---        ┆ ---     ┆ ---     ┆ de         ┆   ┆ te-region  ┆ de        ┆ n-code    ┆ ate-regio │
│ str        ┆ str     ┆ str     ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ n-code    │
│            ┆         ┆         ┆ i64        ┆   ┆ str        ┆ i64       ┆ i64       ┆ ---       │
│            ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆ i64       │
╞════════════╪═════════╪═════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ Afghanista ┆ AF      ┆ AFG     ┆ 4          ┆ … ┆ null       ┆ 142       ┆ 34        ┆ null      │
│ n          ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆           │
│ Åland      ┆ AX      ┆ ALA     ┆ 248        ┆ … ┆ null       ┆ 150       ┆ 154       ┆ null      │
│ Islands    ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆           │
│ Albania    ┆ AL      ┆ ALB     ┆ 8          ┆ … ┆ null       ┆ 150       ┆ 39        ┆ null      │
│ Algeria    ┆ DZ      ┆ DZA     ┆ 12         ┆ … ┆ null       ┆ 2         ┆ 15        ┆ null      │
│ American   ┆ AS      ┆ ASM     ┆ 16         ┆ … ┆ null       ┆ 9         ┆ 61        ┆ null      │
│ Samoa      ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …       ┆ …       ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ Wallis and ┆ WF      ┆ WLF     ┆ 876        ┆ … ┆ null       ┆ 9         ┆ 61        ┆ null      │
│ Futuna     ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆           │
│ Western    ┆ EH      ┆ ESH     ┆ 732        ┆ … ┆ null       ┆ 2         ┆ 15        ┆ null      │
│ Sahara     ┆         ┆         ┆            ┆   ┆            ┆           ┆           ┆           │
│ Yemen      ┆ YE      ┆ YEM     ┆ 887        ┆ … ┆ null       ┆ 142       ┆ 145       ┆ null      │
│ Zambia     ┆ ZM      ┆ ZMB     ┆ 894        ┆ … ┆ Eastern    ┆ 2         ┆ 202       ┆ 14        │
│            ┆         ┆         ┆            ┆   ┆ Africa     ┆           ┆           ┆           │
│ Zimbabwe   ┆ ZW      ┆ ZWE     ┆ 716        ┆ … ┆ Eastern    ┆ 2         ┆ 202       ┆ 14        │
│            ┆         ┆         ┆            ┆   ┆ Africa     ┆           ┆           ┆           │
└────────────┴─────────┴─────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [4]:
# Our data base is in a wide format, we need to convert it to a long format
migrants = migrants_stock.melt(
    id_vars=[
        "index", "destination", "coverage", "type", 
        "destination_code", "origin", "origin_code", "gender"
    ],
    value_vars=["1990", "1995", "2000", "2005", "2010", "2015", "2020", "2024"],
    variable_name="year",
    value_name="migrants"    
)

migrants = migrants.with_columns([
        # year → integer
        pl.col("year").cast(pl.Int32),

        # clean and cast migrants
        (
            pl.col("migrants")
            .cast(pl.Utf8)                               # ensure string ops ok
            # turn common placeholders into nulls
            .replace({"..": None, "—": None, "-": None, "": None, " ":""})
            # remove commas/spaces/other non-digits
            .str.replace_all(r"[^\d.]", "")
            # empty string after cleaning → null
            .map_elements(lambda s: None if s == "" else s, return_dtype=pl.Utf8)
            # finally cast to number; strict=False turns bad leftovers into null
            .cast(pl.Int64, strict=False)
        ).alias("migrants"),

        # clean country orijin and destination names
        pl.col("origin").str.replace_all(r"\*", ""),
        pl.col("destination").str.replace_all(r"\*", ""),

        pl.col("origin_code").alias("M49")

    ])

migrants = migrants.with_columns((pl.col("migrants") / 1_000_000).alias("migrants_millions"))

/var/folders/2l/np27k3x96zlgg9n3dvyy9hxh0000gn/T/ipykernel_40795/1424073704.py:2: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  migrants = migrants_stock.melt(

In [5]:
#we really need to be more carefull about the data 
# we have destinations incluidng agregates like "World" or "High income countries"
# we will filter only the destinations that are countries
migrants

shape: (448_480, 12)
┌───────┬───────────────────┬──────────┬──────┬───┬──────┬──────────┬──────┬───────────────────┐
│ index ┆ destination       ┆ coverage ┆ type ┆ … ┆ year ┆ migrants ┆ M49  ┆ migrants_millions │
│ ---   ┆ ---               ┆ ---      ┆ ---  ┆   ┆ ---  ┆ ---      ┆ ---  ┆ ---               │
│ i64   ┆ str               ┆ str      ┆ str  ┆   ┆ i32  ┆ i64      ┆ i64  ┆ f64               │
╞═══════╪═══════════════════╪══════════╪══════╪═══╪══════╪══════════╪══════╪═══════════════════╡
│ 1     ┆ World             ┆ null     ┆ null ┆ … ┆ 1990 ┆ 77772082 ┆ 900  ┆ 77.772082         │
│ 2     ┆ World             ┆ null     ┆ null ┆ … ┆ 1990 ┆ 7458958  ┆ 1834 ┆ 7.458958          │
│ 3     ┆ World             ┆ null     ┆ null ┆ … ┆ 1990 ┆ 8337422  ┆ 1833 ┆ 8.337422          │
│ 4     ┆ World             ┆ null     ┆ null ┆ … ┆ 1990 ┆ 16862386 ┆ 1831 ┆ 16.862386         │
│ 5     ┆ World             ┆ null     ┆ null ┆ … ┆ 1990 ┆ 7069837  ┆ 1832 ┆ 7.069837          │
│ …     ┆ …                 ┆ …        ┆ …    ┆ … ┆ …    ┆ …        ┆ …    ┆ …                 │
│ 28026 ┆ Wallis and Futuna ┆ 44       ┆ B R  ┆ … ┆ 2024 ┆ 510      ┆ 540  ┆ 0.00051           │
│       ┆ Islands           ┆          ┆      ┆   ┆      ┆          ┆      ┆                   │
│ 28027 ┆ Wallis and Futuna ┆ 44       ┆ B R  ┆ … ┆ 2024 ┆ 28       ┆ 548  ┆ 0.000028          │
│       ┆ Islands           ┆          ┆      ┆   ┆      ┆          ┆      ┆                   │
│ 28028 ┆ Wallis and Futuna ┆ 44       ┆ B R  ┆ … ┆ 2024 ┆ 5        ┆ 957  ┆ 0.000005          │
│       ┆ Islands           ┆          ┆      ┆   ┆      ┆          ┆      ┆                   │
│ 28029 ┆ Wallis and Futuna ┆ 44       ┆ B R  ┆ … ┆ 2024 ┆ 5        ┆ 258  ┆ 0.000005          │
│       ┆ Islands           ┆          ┆      ┆   ┆      ┆          ┆      ┆                   │
│ 28030 ┆ Wallis and Futuna ┆ 44       ┆ B R  ┆ … ┆ 2024 ┆ 13       ┆ 2003 ┆ 0.000013          │
│       ┆ Islands           ┆          ┆      ┆   ┆      ┆          ┆      ┆                   │
└───────┴───────────────────┴──────────┴──────┴───┴──────┴──────────┴──────┴───────────────────┘

In [6]:
# Now I want to include the region and subregion to the main data set 
migrants = migrants.join(country_codes, on="M49", how="inner")
migrants_from_LAC = migrants.filter(pl.col("sub-region")== "Latin America and the Caribbean")
migrants_from_LAC

shape: (51_184, 23)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ intermediat ┆ region-code ┆ sub-region- ┆ intermedia │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ e-region    ┆ ---         ┆ code        ┆ te-region- │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ ---         ┆ i64         ┆ ---         ┆ code       │
│       ┆             ┆          ┆      ┆   ┆ str         ┆             ┆ i64         ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ i64        │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 202   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 203   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 204   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 205   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 206   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26999 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ South       ┆ 19          ┆ 419         ┆ 5          │
│       ┆             ┆          ┆      ┆   ┆ America     ┆             ┆             ┆            │
│ 27000 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ South       ┆ 19          ┆ 419         ┆ 5          │
│       ┆             ┆          ┆      ┆   ┆ America     ┆             ┆             ┆            │
│ 27368 ┆ Micronesia  ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 27419 ┆ Guam        ┆ 38       ┆ B    ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 27597 ┆ Northern    ┆ 39       ┆ B    ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│       ┆ Mariana     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [7]:
migrants_from_LAC.write_csv("../Data/migrants_from_LAC.csv")

In [8]:
# Now lets have total migration (not by gender or by destination country)
# We want to have other indicators by country so we need to have the left part of the data base complete

grouped_LAC = (
    migrants_from_LAC
    .filter(pl.col("destination") == "World")
    
    .group_by(["origin", "M49", "alpha-2", "alpha-3",
               "region", "sub-region", "intermediate-region", "year"])
    
    .agg([
        (pl.col("migrants")/1_000_000).sum().alias("total_migrants"),

        # Sum by gender
        pl.when(pl.col("gender") == "female")
          .then(pl.col("migrants")/1_000_000)
          .otherwise(0)
          .sum()
          .alias("female_migrants"),

        pl.when(pl.col("gender") == "male")
          .then(pl.col("migrants")/1_000_000)
          .otherwise(0)
          .sum()
          .alias("male_migrants"),
    ])
    .with_columns([
        (pl.col("female_migrants") / pl.col("total_migrants") * 100)
        .alias("pct_female_migrants"),

        (pl.col("male_migrants") / pl.col("total_migrants") * 100)
        .alias("pct_male_migrants"),
    ])
    .sort(["origin", "year"])
)

grouped_LAC.filter(pl.col("origin") == "Mexico")

shape: (8, 13)
┌────────┬─────┬─────────┬─────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ origin ┆ M49 ┆ alpha-2 ┆ alpha-3 ┆ … ┆ female_migra ┆ male_migrant ┆ pct_female_m ┆ pct_male_mig │
│ ---    ┆ --- ┆ ---     ┆ ---     ┆   ┆ nts          ┆ s            ┆ igrants      ┆ rants        │
│ str    ┆ i64 ┆ str     ┆ str     ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│        ┆     ┆         ┆         ┆   ┆ f64          ┆ f64          ┆ f64          ┆ f64          │
╞════════╪═════╪═════════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 1.973414     ┆ 2.61546      ┆ 43.004319    ┆ 56.995681    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 3.231673     ┆ 3.933966     ┆ 45.099579    ┆ 54.900421    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 4.19616      ┆ 5.171503     ┆ 44.794096    ┆ 55.205904    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 5.043952     ┆ 6.285584     ┆ 44.520376    ┆ 55.479624    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 5.647673     ┆ 6.461255     ┆ 46.64057     ┆ 53.35943     │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 5.842657     ┆ 6.341569     ┆ 47.952632    ┆ 52.047368    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 5.562762     ┆ 5.889955     ┆ 48.571549    ┆ 51.428451    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 5.665313     ┆ 5.931216     ┆ 48.853523    ┆ 51.146477    │
└────────┴─────┴─────────┴─────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [9]:
import polars as pl

def clean_data_wb(df: pl.DataFrame, variable: str) -> pl.DataFrame:
    """
    Clean a World Bank-style Polars DataFrame by standardizing column names,
    selecting relevant columns, and fixing types.
    """
    df = (
        df.rename({
            "TIME_PERIOD": "year",
            "REF_AREA": "alpha-3",
            "OBS_VALUE": variable
        })
        .select(["year", "alpha-3", variable])
    )

    return df

In [10]:
def world_bank_data(base_df: pl.DataFrame, file_path: str, variable: str):
    new_variable = clean_data_wb(pl.read_csv(Path(file_path), ignore_errors=True), variable)

    complete_df = (
        base_df.join(new_variable, 
        on=["alpha-3", "year"], 
        how="left" )
        .sort(["origin", "year"])
    )

    complete_df.write_csv("../Data/grouped_by_country.csv")

    return complete_df

In [11]:
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WB_KNOMAD_MRI.csv", "remittance_inflows")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WB_WDI_NY_GDP_PCAP_CD.csv","gdp_per_capita")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WB_WDI_SP_POP_TOTL.csv", "total_population")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WB_WDI_SI_POV_GINI.csv", "Gini_index")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WEF_TTDI_HOMICIDERT.csv", "homicides_per_100k_population")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/WB_CLEAR_EXP_DRT.csv", "exposure_to_droughts")
grouped_LAC = world_bank_data(grouped_LAC, "../Data/WB_Data/Climate_risk_INdex.csv", "climate_risk_index")

grouped_LAC = grouped_LAC.with_columns([
    (pl.col("total_population") / 1_000_000).alias("total_population")
])

grouped_LAC = grouped_LAC.with_columns([
    ((pl.col("total_migrants") / pl.col("total_population"))*100).alias("migration_rate")
])

grouped_LAC.write_csv("../Data/grouped_by_country.csv")

grouped_LAC.filter(pl.col("origin") == "Mexico")

shape: (8, 21)
┌────────┬─────┬─────────┬─────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ origin ┆ M49 ┆ alpha-2 ┆ alpha-3 ┆ … ┆ homicides_pe ┆ exposure_to_ ┆ climate_risk ┆ migration_ra │
│ ---    ┆ --- ┆ ---     ┆ ---     ┆   ┆ r_100k_popul ┆ droughts     ┆ _index       ┆ te           │
│ str    ┆ i64 ┆ str     ┆ str     ┆   ┆ ation        ┆ ---          ┆ ---          ┆ ---          │
│        ┆     ┆         ┆         ┆   ┆ ---          ┆ f64          ┆ f64          ┆ f64          │
│        ┆     ┆         ┆         ┆   ┆ f64          ┆              ┆              ┆              │
╞════════╪═════╪═════════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ null         ┆ null         ┆ 5.540769     │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ null         ┆ null         ┆ 7.886249     │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ null         ┆ null         ┆ 9.498211     │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ null         ┆ null         ┆ 10.707282    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ null         ┆ null         ┆ 10.657026    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ 7.8          ┆ null         ┆ 10.063595    │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ 7.2          ┆ null         ┆ 9.032179     │
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ 28.175653    ┆ null         ┆ 112.0        ┆ 8.861715     │
└────────┴─────┴─────────┴─────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [12]:
## I want to show income disparietes as a motivarion to migrate so lets create that data set
## we have 
migrants_from_LAC

shape: (51_184, 23)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ intermediat ┆ region-code ┆ sub-region- ┆ intermedia │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ e-region    ┆ ---         ┆ code        ┆ te-region- │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ ---         ┆ i64         ┆ ---         ┆ code       │
│       ┆             ┆          ┆      ┆   ┆ str         ┆             ┆ i64         ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ i64        │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 202   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 203   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 204   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 205   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 206   ┆ World       ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26999 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ South       ┆ 19          ┆ 419         ┆ 5          │
│       ┆             ┆          ┆      ┆   ┆ America     ┆             ┆             ┆            │
│ 27000 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ South       ┆ 19          ┆ 419         ┆ 5          │
│       ┆             ┆          ┆      ┆   ┆ America     ┆             ┆             ┆            │
│ 27368 ┆ Micronesia  ┆ null     ┆ null ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 27419 ┆ Guam        ┆ 38       ┆ B    ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│ 27597 ┆ Northern    ┆ 39       ┆ B    ┆ … ┆ Caribbean   ┆ 19          ┆ 419         ┆ 29         │
│       ┆ Mariana     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [13]:
country_codes_just_alpha_3 = country_codes.select(["M49", "alpha-3"])

In [14]:
# in order to have the GDP of destination countries we need to add the code of destination 

migrants_from_LAC = (
    migrants_from_LAC.join(
    country_codes_just_alpha_3.with_columns(pl.col("M49").cast(pl.Int64)),
    left_on="destination_code",
    right_on="M49",
    how="left",
    suffix="_dest"
))

In [15]:
migrants_from_LAC

shape: (51_184, 24)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ region-code ┆ sub-region- ┆ intermediat ┆ alpha-3_de │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ ---         ┆ code        ┆ e-region-co ┆ st         │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ i64         ┆ ---         ┆ de          ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆             ┆ i64         ┆ ---         ┆ str        │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ i64         ┆            │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 202   ┆ World       ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ 203   ┆ World       ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ 204   ┆ World       ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ 205   ┆ World       ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ 206   ┆ World       ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26999 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ NZL        │
│ 27000 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ NZL        │
│ 27368 ┆ Micronesia  ┆ null     ┆ null ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ null       │
│ 27419 ┆ Guam        ┆ 38       ┆ B    ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ GUM        │
│ 27597 ┆ Northern    ┆ 39       ┆ B    ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ MNP        │
│       ┆ Mariana     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [16]:
def world_bank_data_dest(base_df: pl.DataFrame, file_path: str, variable: str):
    new_variable = pl.read_csv(Path(file_path), ignore_errors=True)
    
    new_variable = (
        new_variable.rename({
            "TIME_PERIOD": "year",
            "REF_AREA": "alpha-3_dest",
            "OBS_VALUE": variable
        })
        .select(["year", "alpha-3_dest", variable])
    )
    
    complete_df = (
        base_df.join(
            new_variable,
            on=["alpha-3_dest", "year"],
            how="left",
            suffix="_dest"
        )
        .sort(["origin", "year"])
    )

    complete_df.write_csv("../Data/migrants_from_LAC.csv")

    return complete_df

In [17]:
migrants_from_LAC = migrants_from_LAC.filter(pl.col("alpha-3_dest").is_not_null())
migrants_from_LAC

shape: (26_208, 24)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ region-code ┆ sub-region- ┆ intermediat ┆ alpha-3_de │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ ---         ┆ code        ┆ e-region-co ┆ st         │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ i64         ┆ ---         ┆ de          ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆             ┆ i64         ┆ ---         ┆ str        │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ i64         ┆            │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 6938  ┆ Seychelles  ┆ null     ┆ B    ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ SYC        │
│ 7536  ┆ Congo       ┆ null     ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ COG        │
│ 7997  ┆ Egypt       ┆ null     ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ EGY        │
│ 8128  ┆ Libya       ┆ null     ┆ C R  ┆ … ┆ 19          ┆ 419         ┆ 13          ┆ LBY        │
│ 8130  ┆ Libya       ┆ null     ┆ C R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ LBY        │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26998 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ NZL        │
│ 26999 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ NZL        │
│ 27000 ┆ New Zealand ┆ 37       ┆ B R  ┆ … ┆ 19          ┆ 419         ┆ 5           ┆ NZL        │
│ 27419 ┆ Guam        ┆ 38       ┆ B    ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ GUM        │
│ 27597 ┆ Northern    ┆ 39       ┆ B    ┆ … ┆ 19          ┆ 419         ┆ 29          ┆ MNP        │
│       ┆ Mariana     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│       ┆ Islands     ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [18]:
migrants_from_LAC = world_bank_data_dest(migrants_from_LAC, "../Data/WB_Data/WB_WDI_NY_GDP_PCAP_CD.csv","gdp_per_capita_dest")
migrants_from_LAC.filter(pl.col("origin") == "Mexico", pl.col("year") == 2024)

shape: (110, 25)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ sub-region- ┆ intermediat ┆ alpha-3_des ┆ gdp_per_ca │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ code        ┆ e-region-co ┆ t           ┆ pita_dest  │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ ---         ┆ de          ┆ ---         ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆ i64         ┆ ---         ┆ str         ┆ f64        │
│       ┆             ┆          ┆      ┆   ┆             ┆ i64         ┆             ┆            │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 19242 ┆ Portugal    ┆ null     ┆ B    ┆ … ┆ 419         ┆ 13          ┆ PRT         ┆ 28844.4979 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 25         │
│ 20440 ┆ Liechtenste ┆ null     ┆ B    ┆ … ┆ 419         ┆ 13          ┆ LIE         ┆ null       │
│       ┆ in          ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 21602 ┆ Bahamas     ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ BHS         ┆ 39455.4466 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 55         │
│ 25394 ┆ Uruguay     ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ URY         ┆ 23906.5133 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 03         │
│ 22179 ┆ Dominican   ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ DOM         ┆ 10875.6618 │
│       ┆ Republic    ┆          ┆      ┆   ┆             ┆             ┆             ┆ 44         │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26878 ┆ Australia   ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ AUS         ┆ 64407.4842 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 57         │
│ 14696 ┆ Bulgaria    ┆ null     ┆ B    ┆ … ┆ 419         ┆ 13          ┆ BGR         ┆ 17412.4115 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 09         │
│ 20663 ┆ Luxembourg  ┆ null     ┆ B    ┆ … ┆ 419         ┆ 13          ┆ LUX         ┆ 137516.587 │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆             ┆ 324        │
│ 8916  ┆ South       ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ ZAF         ┆ 6253.37158 │
│       ┆ Africa      ┆          ┆      ┆   ┆             ┆             ┆             ┆ 2          │
│ 9273  ┆ Cabo Verde  ┆ null     ┆ B R  ┆ … ┆ 419         ┆ 13          ┆ CPV         ┆ 5272.85253 │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [19]:
migrants_from_LAC = world_bank_data_dest(migrants_from_LAC, "../Data/WB_Data/WB_WDI_SP_POP_TOTL.csv", "total_population_dest")

migrants_from_LAC  = migrants_from_LAC .with_columns([
    (pl.col("total_population_dest") / 1_000_000).alias("total_population_dest")
])

migrants_from_LAC.sort(["origin", "year"]).filter(pl.col("origin") == "Mexico", pl.col("year") == 2024)

shape: (110, 26)
┌───────┬─────────────┬──────────┬──────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ index ┆ destination ┆ coverage ┆ type ┆ … ┆ intermediat ┆ alpha-3_des ┆ gdp_per_cap ┆ total_popu │
│ ---   ┆ ---         ┆ ---      ┆ ---  ┆   ┆ e-region-co ┆ t           ┆ ita_dest    ┆ lation_des │
│ i64   ┆ str         ┆ str      ┆ str  ┆   ┆ de          ┆ ---         ┆ ---         ┆ t          │
│       ┆             ┆          ┆      ┆   ┆ ---         ┆ str         ┆ f64         ┆ ---        │
│       ┆             ┆          ┆      ┆   ┆ i64         ┆             ┆             ┆ f64        │
╞═══════╪═════════════╪══════════╪══════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 19242 ┆ Portugal    ┆ null     ┆ B    ┆ … ┆ 13          ┆ PRT         ┆ 28844.49792 ┆ 10.701636  │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 5           ┆            │
│ 20440 ┆ Liechtenste ┆ null     ┆ B    ┆ … ┆ 13          ┆ LIE         ┆ null        ┆ 0.040197   │
│       ┆ in          ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 21602 ┆ Bahamas     ┆ null     ┆ B R  ┆ … ┆ 13          ┆ BHS         ┆ 39455.44665 ┆ 0.401283   │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 5           ┆            │
│ 25394 ┆ Uruguay     ┆ null     ┆ B R  ┆ … ┆ 13          ┆ URY         ┆ 23906.51330 ┆ 3.386588   │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 3           ┆            │
│ 22179 ┆ Dominican   ┆ null     ┆ B R  ┆ … ┆ 13          ┆ DOM         ┆ 10875.66184 ┆ 11.427557  │
│       ┆ Republic    ┆          ┆      ┆   ┆             ┆             ┆ 4           ┆            │
│ …     ┆ …           ┆ …        ┆ …    ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ 26878 ┆ Australia   ┆ null     ┆ B R  ┆ … ┆ 13          ┆ AUS         ┆ 64407.48425 ┆ 27.204809  │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 7           ┆            │
│ 14696 ┆ Bulgaria    ┆ null     ┆ B    ┆ … ┆ 13          ┆ BGR         ┆ 17412.41150 ┆ 6.444366   │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 9           ┆            │
│ 20663 ┆ Luxembourg  ┆ null     ┆ B    ┆ … ┆ 13          ┆ LUX         ┆ 137516.5873 ┆ 0.677717   │
│       ┆             ┆          ┆      ┆   ┆             ┆             ┆ 24          ┆            │
│ 8916  ┆ South       ┆ null     ┆ B R  ┆ … ┆ 13          ┆ ZAF         ┆ 6253.371582 ┆ 64.007187  │
│       ┆ Africa      ┆          ┆      ┆   ┆             ┆             ┆             ┆            │
│ 9273  ┆ Cabo Verde  ┆ null     ┆ B R  ┆ … ┆ 13          ┆ CPV         ┆ 5272.85253  ┆ 0.524877   │
└───────┴─────────────┴──────────┴──────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [20]:
import polars as pl

df_2024 = migrants_from_LAC.filter(pl.col("year") == 2024)

# Compute the weighted value (GDP × population)
df_2024 = df_2024.with_columns(
    (pl.col("gdp_per_capita_dest") * pl.col("total_population_dest")).alias("weighted_gdp_dest")
)

# Group by origin and sum
df_2024 = (
    df_2024
    .group_by("origin","alpha-3","year" )
    .agg([
        pl.col("total_population_dest").sum().alias("total_pop_dest_sum"),
        pl.col("weighted_gdp_dest").sum().alias("weighted_gdp_dest_sum")
    ])
)

# Compute weighted average of destination GDP
df_2024 = df_2024.with_columns(
    (pl.col("weighted_gdp_dest_sum") / pl.col("total_pop_dest_sum")).alias("weighted_avg_dest_gdp")
)

df_2024.filter(pl.col("origin") == "Mexico")

shape: (1, 6)
┌────────┬─────────┬──────┬────────────────────┬───────────────────────┬───────────────────────┐
│ origin ┆ alpha-3 ┆ year ┆ total_pop_dest_sum ┆ weighted_gdp_dest_sum ┆ weighted_avg_dest_gdp │
│ ---    ┆ ---     ┆ ---  ┆ ---                ┆ ---                   ┆ ---                   │
│ str    ┆ str     ┆ i32  ┆ f64                ┆ f64                   ┆ f64                   │
╞════════╪═════════╪══════╪════════════════════╪═══════════════════════╪═══════════════════════╡
│ Mexico ┆ MEX     ┆ 2024 ┆ 5542.51723         ┆ 1.4035e8              ┆ 25322.255083          │
└────────┴─────────┴──────┴────────────────────┴───────────────────────┴───────────────────────┘

In [21]:
grouped_LAC = grouped_LAC.join(
    df_2024.select(["alpha-3", "year", "weighted_avg_dest_gdp"]),
    on=["alpha-3", "year"],
    how="left"
)
grouped_LAC

grouped_LAC.write_csv("../Data/grouped_by_country.csv")

grouped_LAC.filter(pl.col("origin") == "Mexico", pl.col("year") == 2024)

shape: (1, 22)
┌────────┬─────┬─────────┬─────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ origin ┆ M49 ┆ alpha-2 ┆ alpha-3 ┆ … ┆ exposure_to_ ┆ climate_risk ┆ migration_ra ┆ weighted_avg │
│ ---    ┆ --- ┆ ---     ┆ ---     ┆   ┆ droughts     ┆ _index       ┆ te           ┆ _dest_gdp    │
│ str    ┆ i64 ┆ str     ┆ str     ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│        ┆     ┆         ┆         ┆   ┆ f64          ┆ f64          ┆ f64          ┆ f64          │
╞════════╪═════╪═════════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ Mexico ┆ 484 ┆ MX      ┆ MEX     ┆ … ┆ null         ┆ 112.0        ┆ 8.861715     ┆ 25322.255083 │
└────────┴─────┴─────────┴─────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘